### ISSUE TITLE
Incorrect font size when used with new vector skin

### ISSUE THREAD

**Issue by roysmith** [wikimedia-gadgets/MoreMenu#17]
Go to https://en.wikipedia.org/w/index.php?title=Special:Preferences#mw-prefsection-rendering
Select "Vector" skin
Uncheck "Use Legacy Vector"
Save
Go to any wiki page.

Open the "Page" drop-down menu

The "Move" item is in a smaller font size than all the others.  Originally filed as https://phabricator.wikimedia.org/T291780, which was closed as being a MoreMenu bug, apparently due to not using mw.util.addPortletLink.

<img width="251" alt="Screen Shot 2021-09-26 at 10 58 18 AM" src="https://user-images.githubusercontent.com/704337/134986637-52e547ae-858b-4ca7-8a16-ee9d2568e72f.png">

**Comment by jdlrobson** [comment]
Let me know if I can help in any way!

FYI the `mw.util.addPortletLink` method is undergoing some changes that should be available this week which should guarantee menu consistency across skins for this kind of thing.

**Comment by MusikAnimal** [comment]
The issue here is that new Vector wants a `<span>` around the text inside the links, while old Vector does not. The reason the "Move" item looks correct is because it isn't _added_ by MoreMenu, rather _moved_ from the native "More" menu.

Since no skin supports submenus, I'm not sure we'd be able to fully get away with using `mw.util.addPortletLink`. I just checked and it does happen to work if I give it the ID of the a submenu, so we might be able to use for Vector at least. Other skins still require hacks. MoreMenu also needs to give menu items additional CSS classes which addPortletLink isn't capable of, but since it returns the `HTMLElement` we can append the CSS classes separately, I suppose.

**Comment by jdlrobson** [comment]
The span is now taken care of by addPortletLink. That's available for testing on the beta cluster, and will be in production everywhere on Thursday providing the train goes to plan. 

You should be able to use addPortletLink on menus crafted by the gadget.

**Comment by jdlrobson** [comment]
(I forgot to add that old Vector will now be added the span as well so there is a risk this problem might surface on old Vector with this weeks train)

**Comment by MusikAnimal** [comment]
Fixed. I'm still not using addPortletLink, but will look into that in the future.
