### ISSUE TITLE
vector-menu-heading for h3 label

### ISSUE THREAD

**Issue by libkoi** [wikimedia-gadgets/MoreMenu#25]
Seems in the latest MediaWiki version, a "vector-menu-heading" class is required for h3 label text (see group 0 sites for its appearance). Because of this, I suggest adding `class="vector-menu-heading"` to [L687](https://github.com/wikimedia-gadgets/MoreMenu/blob/master/src/MoreMenu.js#L687). 
Not really sure about how to modify the code (it looks different from the version on metawiki), so I create an issue rather than a PR. Thanks a lot!

**Comment by MusikAnimal** [comment]
Yep, I've got a fix ready to deploy, but unfortunately I can't do it until Thursday, otherwise it will break MoreMenu for those still on MW 1.38.0-wmf.24. So stay tuned :) Everything should still be functional in the meantime, at least.

**Comment by MusikAnimal** [comment]
Resolved

**Comment by jdlrobson** [comment]
Hey @MusikAnimal sorry for the lack of a heads up on this one. I was out on vacation.

I suggest we set up some kind of cron job pointing to the beta cluster to check for these sort of changes as my awareness  of how these styles are being used doesn't seem to be scaling. Alternatively we might consider serving duplicate CSS for this feature so that it's safe from refactorings. We have some much larger refactors planned as part of  https://phabricator.wikimedia.org/T302073 (see prototype) so there is going to be continued friction here unless we future proof this code in some way.

What do you think?

**Comment by MusikAnimal** [comment]
@jdlrobson I'm glad you brought it up! I nearly commented at T290280 to ask why Tech News wasn't used, but I figured maybe you all didn't know it was going to cause breakage to gadgets. However the QA phase seemed to spot this... https://phabricator.wikimedia.org/T290280#7764249 (though I'm sure the MoreMenu on Beta is outdated as it is). I also didn't think there was a backwards-compatible fix, although it turned out there was by using `.vector-menu-heading` but not the `<label>`. Additionally, the patch was authored by a new contributor who may not have been aware of Tech News and the Wikimedia ecosystem.

Anyway, I think we need a JS entry point to create new menus (or portlets I guess they are called). `mw.util.addPortletLink` is great but it only lets you add to existing elements/menus, right? I'm thinking we need something like `mw.util.addPortlet( locationId, id, label )` (where `location` is `right-navigation` or `mw-panel`) onto which I can then use `mw.util.addPortletLink`. If that's introduced we don't need to hardcode any HTML (except for submenus, and that's okay I think).

T302073 for sure is going to require a radical reworking of how build custom menus (please feel free to add #user-notice as appropriate so it's not forgotten), but if we have a reliable `mw.util.addPortlet` I think we'd be safe from your planned changes.

**Comment by jdlrobson** [comment]
I dont think an addPortlet method is viable here as all skins produce different HTML for the same portlet and many use Mustache templates. We'd have to ship a client version of Mustache and the template and some how vary the method based on skin.

One thing that might work better is cloning the more menu and deducing HTML structure from the result. Another way is to ship dedicated CSS with the gadget. While this would still cause inconsistencies as Vector evolves at least it wouldnt drastically break the menu.

**Comment by MusikAnimal** [comment]
> I dont think an addPortlet method is viable here as all skins produce different HTML for the same portlet and many use Mustache templates. We'd have to ship a client version of Mustache and the template to all users and somehow vary the method based on skin.

The issue (for Twinkle and MoreMenu) is solely with menus, which (at Wikimedia) is unique to Vector, thus I think introducing this JS method as part of Vector would still be sensible. In fact I think it would see widespread use; creating a new menu is a lot more convenient for a collection of links rather than piling them all into #p-cactions or elsewhere. Gadgets and scripts often already have skin-specific logic, and could simply fallback to using #p-actions or what have you for non-Vector.

As for Mustache, that is [shipped with Core](https://www.mediawiki.org/wiki/Manual:HTML_templates), right? If the `mw.util.addPortlet` method were to go into Core,  it could perhaps expect skins to implement the rendering part, first checking if there's a Mustache template and rendering that if given. If no child rendering method is given by the skin, it could simply fallback to a standard portlet such as `#p-actions` or `#p-navigation`, depending on which `locationId` it is given. But if it came down to it, I still feel this is still really a Vector problem, not MediaWiki in general, so it's OK to put the focus there.

These are just ideas. It's all easier said then done, of course! Tomorrow I can create a task with the problem statement, then hopefully we can wider input on devising a solution.

> One thing that might work better is cloning the more menu and deducing HTML structure from the result.

Good idea. That might be what I do for the short-term, if necessary.

The Article Tools prototype looks awesome, by the way!

**Comment by jdlrobson** [comment]
A Vector only API seems more doable, especially if it can be asychronous but I think it could be tricky to build out right now while menus are a moving target.

I think some snapshot/UI regression tests would also help here.
